### ISSUE TITLE
SVG's are only rendering the first available path - because the rest are being nested.

### ISSUE THREAD

**Issue by vonKristoff** [evil-icons/gulp-evil-icons#3] opened 2015-01-12 11:48 UTC
Hi,
I have a little problem with the plugin now that only one path of the icon is rendered because the rest of the paths are nested within each other, which means that the svg only reads the first path and fails for the rest, which leaves an unfinished icon! 

The render will prepend svg link/paths to the body first (svg xmlns), and upon investigating them is where the nesting issue takes place - see below:

```
<symbol id="ei-archive-icon" viewBox="0 0 50 50"><path d="M42 20h-2v-5c0-.6-.4-1-1-1H11c-.6 0-1 .4-1 1v5H8v-5c0-1.7 1.3-3 3-3h28c1.7 0 3 1.3 3 3v5z"><path d="M37 40H13c-1.7 0-3-1.3-3-3V20h2v17c0 .6.4 1 1 1h24c.6 0 1-.4 1-1V20h2v17c0 1.7-1.3 3-3 3z"><path d="M29 26h-8c-.6 0-1-.4-1-1s.4-1 1-1h8c.6 0 1 .4 1 1s-.4 1-1 1z"><path d="M8 18h34v2H8z"></path></path></path></path></symbol>
```

At the end you will find x4 closing path tags in a row.. The paths shouldn't be nested for the svg's to be displayed correctly.

Thanks

**Comment by madyankin** [comment] 2015-01-12 12:00
Hi, 
Do you invoke the icons plugin before jade, don't you? May I see the config?

**Comment by madyankin** [comment] 2015-01-12 12:01
It seems like this issue is a duplicate of #2.

**Comment by vonKristoff** [comment] 2015-01-12 12:08
lol - must have got posted at the same time! yes definitely a duplicate - you can close this issue and ill follow the one you've already commented on - ps config included..

```
gulp.task('jade',function() {
  gulp.src('./jade/**/*.jade')
    .pipe(jade())
    .pipe(evil())
    .pipe(gulp.dest('../'))
    .pipe(refresh())
})
```

my build src is /
my dev (where gulpfile is) is /dev

**Comment by madyankin** [comment] 2015-01-12 12:11
I'll investigate this problem, thank you for the report.

**Closed as completed** 2015-01-12 12:11 UTC
